name: Linute Recovery Build

on:
  workflow_dispatch: # Это создаст кнопку запуска

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Linute
        uses: OrangeFoxRecovery/OrangeFox-Builder@main
        with:
          DEVICE_NAME: fog
          DEVICE_TREE: https://github.com
          DEVICE_TREE_BRANCH: lineage-23.0
          BUILD_TARGET: recovery
          
