name: Linute Recovery Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential zip curl libc6-dev libncurses5-dev libssl-dev python3 repo

      - name: Setup Linute (OrangeFox) Sync
        run: |
          mkdir ~/orangefox
          cd ~/orangefox
          git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          
          # Твоя новая правильная ссылка
          repo init --no-repo-verify --depth=1 -u https://github.com/OrangeFoxRecovery/fox-6.0_manifest -b fox-6.0
          
          # Начинаем качать (теперь точно должно пойти!)
          repo sync -j$(nproc --all) --force-sync --no-tags --no-clone-bundle --prune




          
      - name: Clone Device Tree
        run: |
          cd ~/orangefox
          git clone https://github.com -b lineage-23.0 device/xiaomi/fog

      - name: Start Compilation
        run: |
          echo "Здесь начнется магия сборки Linute..."
