name: Linute Recovery Build

on:
  workflow_dispatch: # Позволяет запускать сборку кнопкой вручную

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cleanup Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential zip curl libc6-dev libncurses5-dev libssl-dev python3

      - name: Sync Sources
        run: |
          echo "Здесь мы пропишем команды для скачивания исходников TWRP/Linute"
